language: java
jdk:
  - openjdk8

branches:
  only:
    - master
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - roeniss2@gmail.com

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy && cd ..
  - mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/webapp.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: cicd-jar-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: cicd-jar-bucket
    key: webapp.zip
    region: ap-northeast-2
    bundle_type: zip
    application: hyangro-web-deploy
    deployment_group: web-deploy-group
    wait-until-deployed: true

